// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.2
// source: calculator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Solicitud de números por el cliente
type NumberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` // Identificador del cliente
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumberRequest) Reset() {
	*x = NumberRequest{}
	mi := &file_calculator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberRequest) ProtoMessage() {}

func (x *NumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberRequest.ProtoReflect.Descriptor instead.
func (*NumberRequest) Descriptor() ([]byte, []int) {
	return file_calculator_proto_rawDescGZIP(), []int{0}
}

func (x *NumberRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// Respuesta con vector de números
type NumberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Available     bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`                              // Si hay números disponibles
	VectorId      string                 `protobuf:"bytes,2,opt,name=vector_id,json=vectorId,proto3" json:"vector_id,omitempty"`                 // ID único del vector
	Num1          int32                  `protobuf:"varint,3,opt,name=num1,proto3" json:"num1,omitempty"`                                        // Primer número (1-1000)
	Num2          int32                  `protobuf:"varint,4,opt,name=num2,proto3" json:"num2,omitempty"`                                        // Segundo número (1-1000)
	Num3          int32                  `protobuf:"varint,5,opt,name=num3,proto3" json:"num3,omitempty"`                                        // Tercer número (1-1000)
	SystemStopped bool                   `protobuf:"varint,6,opt,name=system_stopped,json=systemStopped,proto3" json:"system_stopped,omitempty"` // Si el sistema alcanzó 1 millón de resultados
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumberResponse) Reset() {
	*x = NumberResponse{}
	mi := &file_calculator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberResponse) ProtoMessage() {}

func (x *NumberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberResponse.ProtoReflect.Descriptor instead.
func (*NumberResponse) Descriptor() ([]byte, []int) {
	return file_calculator_proto_rawDescGZIP(), []int{1}
}

func (x *NumberResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *NumberResponse) GetVectorId() string {
	if x != nil {
		return x.VectorId
	}
	return ""
}

func (x *NumberResponse) GetNum1() int32 {
	if x != nil {
		return x.Num1
	}
	return 0
}

func (x *NumberResponse) GetNum2() int32 {
	if x != nil {
		return x.Num2
	}
	return 0
}

func (x *NumberResponse) GetNum3() int32 {
	if x != nil {
		return x.Num3
	}
	return 0
}

func (x *NumberResponse) GetSystemStopped() bool {
	if x != nil {
		return x.SystemStopped
	}
	return false
}

// Solicitud de resultado procesado
type ResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` // ID del cliente
	VectorId      string                 `protobuf:"bytes,2,opt,name=vector_id,json=vectorId,proto3" json:"vector_id,omitempty"` // ID del vector procesado
	Result        int32                  `protobuf:"varint,3,opt,name=result,proto3" json:"result,omitempty"`                    // Resultado de la operación matemática
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultRequest) Reset() {
	*x = ResultRequest{}
	mi := &file_calculator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultRequest) ProtoMessage() {}

func (x *ResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultRequest.ProtoReflect.Descriptor instead.
func (*ResultRequest) Descriptor() ([]byte, []int) {
	return file_calculator_proto_rawDescGZIP(), []int{2}
}

func (x *ResultRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ResultRequest) GetVectorId() string {
	if x != nil {
		return x.VectorId
	}
	return ""
}

func (x *ResultRequest) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

// Respuesta de confirmación
type ResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`                                // Si el resultado fue aceptado
	TotalResults  int64                  `protobuf:"varint,2,opt,name=total_results,json=totalResults,proto3" json:"total_results,omitempty"`    // Total de resultados recibidos
	SystemStopped bool                   `protobuf:"varint,3,opt,name=system_stopped,json=systemStopped,proto3" json:"system_stopped,omitempty"` // Si el sistema debe detenerse
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultResponse) Reset() {
	*x = ResultResponse{}
	mi := &file_calculator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultResponse) ProtoMessage() {}

func (x *ResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultResponse.ProtoReflect.Descriptor instead.
func (*ResultResponse) Descriptor() ([]byte, []int) {
	return file_calculator_proto_rawDescGZIP(), []int{3}
}

func (x *ResultResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ResultResponse) GetTotalResults() int64 {
	if x != nil {
		return x.TotalResults
	}
	return 0
}

func (x *ResultResponse) GetSystemStopped() bool {
	if x != nil {
		return x.SystemStopped
	}
	return false
}

var File_calculator_proto protoreflect.FileDescriptor

const file_calculator_proto_rawDesc = "" +
	"\n" +
	"\x10calculator.proto\x12\n" +
	"calculator\",\n" +
	"\rNumberRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"\xae\x01\n" +
	"\x0eNumberResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12\x1b\n" +
	"\tvector_id\x18\x02 \x01(\tR\bvectorId\x12\x12\n" +
	"\x04num1\x18\x03 \x01(\x05R\x04num1\x12\x12\n" +
	"\x04num2\x18\x04 \x01(\x05R\x04num2\x12\x12\n" +
	"\x04num3\x18\x05 \x01(\x05R\x04num3\x12%\n" +
	"\x0esystem_stopped\x18\x06 \x01(\bR\rsystemStopped\"a\n" +
	"\rResultRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1b\n" +
	"\tvector_id\x18\x02 \x01(\tR\bvectorId\x12\x16\n" +
	"\x06result\x18\x03 \x01(\x05R\x06result\"x\n" +
	"\x0eResultResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12#\n" +
	"\rtotal_results\x18\x02 \x01(\x03R\ftotalResults\x12%\n" +
	"\x0esystem_stopped\x18\x03 \x01(\bR\rsystemStopped2\x9e\x01\n" +
	"\x10ProducerConsumer\x12C\n" +
	"\n" +
	"GetNumbers\x12\x19.calculator.NumberRequest\x1a\x1a.calculator.NumberResponse\x12E\n" +
	"\fSubmitResult\x12\x19.calculator.ResultRequest\x1a\x1a.calculator.ResultResponseB\x12Z\x10calculator/protob\x06proto3"

var (
	file_calculator_proto_rawDescOnce sync.Once
	file_calculator_proto_rawDescData []byte
)

func file_calculator_proto_rawDescGZIP() []byte {
	file_calculator_proto_rawDescOnce.Do(func() {
		file_calculator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_calculator_proto_rawDesc), len(file_calculator_proto_rawDesc)))
	})
	return file_calculator_proto_rawDescData
}

var file_calculator_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_calculator_proto_goTypes = []any{
	(*NumberRequest)(nil),  // 0: calculator.NumberRequest
	(*NumberResponse)(nil), // 1: calculator.NumberResponse
	(*ResultRequest)(nil),  // 2: calculator.ResultRequest
	(*ResultResponse)(nil), // 3: calculator.ResultResponse
}
var file_calculator_proto_depIdxs = []int32{
	0, // 0: calculator.ProducerConsumer.GetNumbers:input_type -> calculator.NumberRequest
	2, // 1: calculator.ProducerConsumer.SubmitResult:input_type -> calculator.ResultRequest
	1, // 2: calculator.ProducerConsumer.GetNumbers:output_type -> calculator.NumberResponse
	3, // 3: calculator.ProducerConsumer.SubmitResult:output_type -> calculator.ResultResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_calculator_proto_init() }
func file_calculator_proto_init() {
	if File_calculator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_calculator_proto_rawDesc), len(file_calculator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_calculator_proto_goTypes,
		DependencyIndexes: file_calculator_proto_depIdxs,
		MessageInfos:      file_calculator_proto_msgTypes,
	}.Build()
	File_calculator_proto = out.File
	file_calculator_proto_goTypes = nil
	file_calculator_proto_depIdxs = nil
}
