// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/pubsub.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to subscribe to queues
type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      int32                  `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Queues        []string               `protobuf:"bytes,2,rep,name=queues,proto3" json:"queues,omitempty"` // "primary", "secondary", "tertiary"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_proto_pubsub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pubsub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_pubsub_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetClientId() int32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *SubscribeRequest) GetQueues() []string {
	if x != nil {
		return x.Queues
	}
	return nil
}

// A set of numbers published to a queue
type NumberSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int32                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Numbers       []int32                `protobuf:"varint,2,rep,packed,name=numbers,proto3" json:"numbers,omitempty"`
	Queue         string                 `protobuf:"bytes,3,opt,name=queue,proto3" json:"queue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumberSet) Reset() {
	*x = NumberSet{}
	mi := &file_proto_pubsub_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumberSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberSet) ProtoMessage() {}

func (x *NumberSet) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pubsub_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberSet.ProtoReflect.Descriptor instead.
func (*NumberSet) Descriptor() ([]byte, []int) {
	return file_proto_pubsub_proto_rawDescGZIP(), []int{1}
}

func (x *NumberSet) GetMessageId() int32 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *NumberSet) GetNumbers() []int32 {
	if x != nil {
		return x.Numbers
	}
	return nil
}

func (x *NumberSet) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

// Result sent by client after processing
type ResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      int32                  `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	MessageId     int32                  `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Result        int32                  `protobuf:"varint,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultRequest) Reset() {
	*x = ResultRequest{}
	mi := &file_proto_pubsub_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultRequest) ProtoMessage() {}

func (x *ResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pubsub_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultRequest.ProtoReflect.Descriptor instead.
func (*ResultRequest) Descriptor() ([]byte, []int) {
	return file_proto_pubsub_proto_rawDescGZIP(), []int{2}
}

func (x *ResultRequest) GetClientId() int32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *ResultRequest) GetMessageId() int32 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *ResultRequest) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type ResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultResponse) Reset() {
	*x = ResultResponse{}
	mi := &file_proto_pubsub_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultResponse) ProtoMessage() {}

func (x *ResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pubsub_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultResponse.ProtoReflect.Descriptor instead.
func (*ResultResponse) Descriptor() ([]byte, []int) {
	return file_proto_pubsub_proto_rawDescGZIP(), []int{3}
}

func (x *ResultResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_proto_pubsub_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pubsub_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_pubsub_proto_rawDescGZIP(), []int{4}
}

type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalResults  int32                  `protobuf:"varint,1,opt,name=total_results,json=totalResults,proto3" json:"total_results,omitempty"`
	TotalSum      int32                  `protobuf:"varint,2,opt,name=total_sum,json=totalSum,proto3" json:"total_sum,omitempty"`
	Clients       []*ClientStats         `protobuf:"bytes,3,rep,name=clients,proto3" json:"clients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_proto_pubsub_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pubsub_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_pubsub_proto_rawDescGZIP(), []int{5}
}

func (x *StatsResponse) GetTotalResults() int32 {
	if x != nil {
		return x.TotalResults
	}
	return 0
}

func (x *StatsResponse) GetTotalSum() int32 {
	if x != nil {
		return x.TotalSum
	}
	return 0
}

func (x *StatsResponse) GetClients() []*ClientStats {
	if x != nil {
		return x.Clients
	}
	return nil
}

type ClientStats struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ClientId         int32                  `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	SubscribedQueues []string               `protobuf:"bytes,2,rep,name=subscribed_queues,json=subscribedQueues,proto3" json:"subscribed_queues,omitempty"`
	ResultsCount     int32                  `protobuf:"varint,3,opt,name=results_count,json=resultsCount,proto3" json:"results_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ClientStats) Reset() {
	*x = ClientStats{}
	mi := &file_proto_pubsub_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientStats) ProtoMessage() {}

func (x *ClientStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pubsub_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientStats.ProtoReflect.Descriptor instead.
func (*ClientStats) Descriptor() ([]byte, []int) {
	return file_proto_pubsub_proto_rawDescGZIP(), []int{6}
}

func (x *ClientStats) GetClientId() int32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *ClientStats) GetSubscribedQueues() []string {
	if x != nil {
		return x.SubscribedQueues
	}
	return nil
}

func (x *ClientStats) GetResultsCount() int32 {
	if x != nil {
		return x.ResultsCount
	}
	return 0
}

var File_proto_pubsub_proto protoreflect.FileDescriptor

const file_proto_pubsub_proto_rawDesc = "" +
	"\n" +
	"\x12proto/pubsub.proto\x12\x06pubsub\"G\n" +
	"\x10SubscribeRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x05R\bclientId\x12\x16\n" +
	"\x06queues\x18\x02 \x03(\tR\x06queues\"Z\n" +
	"\tNumberSet\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x05R\tmessageId\x12\x18\n" +
	"\anumbers\x18\x02 \x03(\x05R\anumbers\x12\x14\n" +
	"\x05queue\x18\x03 \x01(\tR\x05queue\"c\n" +
	"\rResultRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x05R\bclientId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x05R\tmessageId\x12\x16\n" +
	"\x06result\x18\x03 \x01(\x05R\x06result\"*\n" +
	"\x0eResultResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x0e\n" +
	"\fStatsRequest\"\x80\x01\n" +
	"\rStatsResponse\x12#\n" +
	"\rtotal_results\x18\x01 \x01(\x05R\ftotalResults\x12\x1b\n" +
	"\ttotal_sum\x18\x02 \x01(\x05R\btotalSum\x12-\n" +
	"\aclients\x18\x03 \x03(\v2\x13.pubsub.ClientStatsR\aclients\"|\n" +
	"\vClientStats\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x05R\bclientId\x12+\n" +
	"\x11subscribed_queues\x18\x02 \x03(\tR\x10subscribedQueues\x12#\n" +
	"\rresults_count\x18\x03 \x01(\x05R\fresultsCount2\xc1\x01\n" +
	"\rPubSubService\x12:\n" +
	"\tSubscribe\x12\x18.pubsub.SubscribeRequest\x1a\x11.pubsub.NumberSet0\x01\x12;\n" +
	"\n" +
	"SendResult\x12\x15.pubsub.ResultRequest\x1a\x16.pubsub.ResultResponse\x127\n" +
	"\bGetStats\x12\x14.pubsub.StatsRequest\x1a\x15.pubsub.StatsResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_pubsub_proto_rawDescOnce sync.Once
	file_proto_pubsub_proto_rawDescData []byte
)

func file_proto_pubsub_proto_rawDescGZIP() []byte {
	file_proto_pubsub_proto_rawDescOnce.Do(func() {
		file_proto_pubsub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_pubsub_proto_rawDesc), len(file_proto_pubsub_proto_rawDesc)))
	})
	return file_proto_pubsub_proto_rawDescData
}

var file_proto_pubsub_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_pubsub_proto_goTypes = []any{
	(*SubscribeRequest)(nil), // 0: pubsub.SubscribeRequest
	(*NumberSet)(nil),        // 1: pubsub.NumberSet
	(*ResultRequest)(nil),    // 2: pubsub.ResultRequest
	(*ResultResponse)(nil),   // 3: pubsub.ResultResponse
	(*StatsRequest)(nil),     // 4: pubsub.StatsRequest
	(*StatsResponse)(nil),    // 5: pubsub.StatsResponse
	(*ClientStats)(nil),      // 6: pubsub.ClientStats
}
var file_proto_pubsub_proto_depIdxs = []int32{
	6, // 0: pubsub.StatsResponse.clients:type_name -> pubsub.ClientStats
	0, // 1: pubsub.PubSubService.Subscribe:input_type -> pubsub.SubscribeRequest
	2, // 2: pubsub.PubSubService.SendResult:input_type -> pubsub.ResultRequest
	4, // 3: pubsub.PubSubService.GetStats:input_type -> pubsub.StatsRequest
	1, // 4: pubsub.PubSubService.Subscribe:output_type -> pubsub.NumberSet
	3, // 5: pubsub.PubSubService.SendResult:output_type -> pubsub.ResultResponse
	5, // 6: pubsub.PubSubService.GetStats:output_type -> pubsub.StatsResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_pubsub_proto_init() }
func file_proto_pubsub_proto_init() {
	if File_proto_pubsub_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_pubsub_proto_rawDesc), len(file_proto_pubsub_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_pubsub_proto_goTypes,
		DependencyIndexes: file_proto_pubsub_proto_depIdxs,
		MessageInfos:      file_proto_pubsub_proto_msgTypes,
	}.Build()
	File_proto_pubsub_proto = out.File
	file_proto_pubsub_proto_goTypes = nil
	file_proto_pubsub_proto_depIdxs = nil
}
